apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vectoraggregators.vector.zcentric.com
  labels: {{- include "vector-operator-crds.labels" . | nindent 4}}
spec:
  group: vector.zcentric.com
  names:
    kind: VectorAggregator
    listKind: VectorAggregatorList
    plural: vectoraggregators
    singular: vectoraggregator
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.image
          name: Image
          type: string
        - jsonPath: .spec.replicas
          name: Replicas
          type: integer
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: VectorAggregator is the Schema for the vectoraggregators API
          properties:
            apiVersion:
              description: APIVersion defines the versioned schema of this representation of an object.
              type: string
            kind:
              description: Kind is a string value representing the REST resource this object represents.
              type: string
            metadata:
              type: object
            spec:
              description: VectorAggregatorSpec defines the desired state of VectorAggregator
              properties:
                api:
                  description: API configuration for Vector
                  properties:
                    address:
                      default: 0.0.0.0:8686
                      description: Address is the address to bind the API server to
                      type: string
                    enabled:
                      default: false
                      description: Enabled determines if the API server should be enabled
                      type: boolean
                    playground:
                      default: false
                      description: Playground determines if the GraphQL playground should be enabled
                      type: boolean
                  type: object
                data_dir:
                  default: /tmp/vector-data-dir
                  description: DataDir specifies the data directory for Vector
                  type: string
                expire_metrics_secs:
                  default: 30
                  description: ExpireMetricsSecs specifies how long to keep metrics before expiring them
                  format: int32
                  type: integer
                image:
                  description: Image specifies the Vector container image to use
                  type: string
                replicas:
                  default: 1
                  description: Replicas is the number of Vector pods to run
                  format: int32
                  minimum: 0
                  type: integer
                serviceAccount:
                  description: ServiceAccount configuration for Vector
                  properties:
                    annotations:
                      additionalProperties:
                        type: string
                      description: Annotations to be added to the ServiceAccount
                      type: object
                  type: object
                tolerations:
                  description: Tolerations defines the pod's tolerations
                  items:
                    description: The pod this Toleration is attached to tolerates any taint that matches the triple <key,value,effect> using the matching operator <operator>.
                    properties:
                      effect:
                        description: Effect indicates the taint effect to match. Empty means match all taint effects.
                        type: string
                      key:
                        description: Key is the taint key that the toleration applies to. Empty means match all taint keys.
                        type: string
                      operator:
                        description: Operator represents a key's relationship to the value.
                        type: string
                      tolerationSeconds:
                        description: TolerationSeconds represents the period of time the toleration tolerates the taint.
                        format: int64
                        type: integer
                      value:
                        description: Value is the taint value the toleration matches to.
                        type: string
                    type: object
                  type: array
              required:
                - image
              type: object
            status:
              description: VectorAggregatorStatus defines the observed state of VectorAggregator
              properties:
                conditions:
                  description: Conditions represent the latest available observations of VectorAggregator's state
                  items:
                    description: Condition contains details for one aspect of the current state of this API Resource.
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        type: string
                      observedGeneration:
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        type: string
                      status:
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                        type: string
                      type:
                        type: string
                    required:
                      - lastTransitionTime
                      - message
                      - reason
                      - status
                      - type
                    type: object
                  type: array
                configHash:
                  description: ConfigHash represents the current hash of the Vector configuration
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
