apiVersion: vector.zcentric.com/v1alpha1
kind: Vector
metadata:
  name: vector-agent-complete
spec:
  image: timberio/vector:0.34.0-debian
  api:
    enabled: true
    address: "0.0.0.0:8686"
    playground: true
  data_dir: "/var/lib/vector"
  expire_metrics_secs: 30
  serviceAccount:
    annotations:
      example.com/annotation: "value"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  env:
    - name: VECTOR_LOG
      value: "debug"
    - name: VECTOR_THREADS
      value: "2"
    - name: VECTOR_CONFIG_YAML
      valueFrom:
        configMapKeyRef:
          name: vector-config
          key: config.yaml
    - name: VECTOR_DATADOG_API_KEY
      valueFrom:
        secretKeyRef:
          name: vector-secrets
          key: datadog-api-key
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
---

apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vector-agent-complete-base
spec:
  vectorRef: vector-agent-complete
  sources:
    logs:
      type: "kubernetes_logs"

  sinks:
    stdout:
      type: "console"
      encoding:
        codec: "json"
      inputs:
        - filter
---
apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vector-agent-complete-b
spec:
  vectorRef: vector-agent-complete
  transforms:
    addTeam:
      type: "remap"
      inputs:
        - logs
      source: |
        .team = "teamA"
    filter:
      type: "filter"
      inputs:
        - addTeam
      condition:
        type: "vrl"
        source: ".status != 200"