
apiVersion: vector.zcentric.com/v1alpha1
kind: VectorAggregator
metadata:
  name: vector-aggregator-complete
spec:
  image: "timberio/vector:0.38.0-distroless-libc"
  # Optional deployment configuration
  replicas: 1               # Default value is 1
  # Optional API configuration
  api:
    address: "0.0.0.0:8686"  # Default value
    enabled: true            # Enable API for monitoring
    playground: false        # Enable GraphQL playground for testing
  # Optional Vector configuration
  data_dir: "/tmp/vector-data-dir"  # Default value
  expire_metrics_secs: 30           # Default value
  # Optional ServiceAccount configuration
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/vector-role"  # Example AWS IRSA annotation
  # Optional tolerations configuration
  tolerations:
    - operator: Exists
---
apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vectorpipeline-aggregator-complete
spec:
  vectorRef: vector-aggregator-complete
  sources:
    source1:
      type: "kubernetes_logs"
  sinks:
    console:
      type: "console"
      encoding:
        codec: "json"
      inputs:
        - source1
