apiVersion: vector.zcentric.com/v1alpha1
kind: Vector
metadata:
  name: vector-agent-minimal
spec:
  image: timberio/vector:0.34.0-debian
---

apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vector-agent-minimal-base
spec:
  vectorRef: vector-agent-minimal
  sources:
    logs:
      type: "kubernetes_logs"