# Minimal agent example
apiVersion: vector.zcentric.com/v1alpha1
kind: Vector
metadata:
  name: vector-agent-minimal
  namespace: vector
spec:
  type: agent
  image: "timberio/vector:0.38.0-distroless-libc"
---
# Complete agent example with all optional fields
apiVersion: vector.zcentric.com/v1alpha1
kind: Vector
metadata:
  name: vector-agent-complete
  namespace: vector
spec:
  type: agent
  image: "timberio/vector:0.38.0-distroless-libc"
  # Optional API configuration
  api:
    address: "0.0.0.0:8686"  # Default value
    enabled: false           # Default value
    playground: false        # Default value
  # Optional Vector configuration
  data_dir: "/tmp/vector-data-dir"  # Default value
  expire_metrics_secs: 30           # Default value
  # Optional ServiceAccount configuration
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/vector-role"  # Example AWS IRSA annotation
---
# Minimal aggregator example
apiVersion: vector.zcentric.com/v1alpha1
kind: Vector
metadata:
  name: vector-aggregator-minimal
  namespace: vector
spec:
  type: aggregator
  image: "timberio/vector:0.38.0-distroless-libc"
---
# Complete aggregator example with all optional fields
apiVersion: vector.zcentric.com/v1alpha1
kind: Vector
metadata:
  name: vector-aggregator-complete
  namespace: vector
spec:
  type: aggregator
  image: "timberio/vector:0.38.0-distroless-libc"
  # Optional deployment configuration
  replicas: 2               # Default value is 1
  # Optional API configuration
  api:
    address: "0.0.0.0:8686"  # Default value
    enabled: true            # Enable API for monitoring
    playground: true         # Enable GraphQL playground for testing
  # Optional Vector configuration
  data_dir: "/tmp/vector-data-dir"  # Default value
  expire_metrics_secs: 30           # Default value
  # Optional ServiceAccount configuration
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/vector-role"  # Example AWS IRSA annotation
