apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vectorpipeline-sample
spec:
  vectorRef: vector-agent-complete
  sources:
    source1:
      type: "kubernetes_logs"
      extra_label_selector: "app!=testdeployment"
    source2:
      type: "kubernetes_logs"
      extra_label_selector: "app!=testdeployment1"
  transforms:
    remap:
      type: "remap"
      inputs:
        - source1
      source: |
        .@timestamp = del(.timestamp)
        .testField = "testValuevalue"
    filter:
      type: "filter"
      inputs:
        - source2
      condition:
        type: "vrl"
        source: ".status != 200"
  sinks:
    test222:
      type: "console"
      encoding:
        codec: "json"
      inputs:
        - filter
        - remap
---
apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vectorpipeline-team2
spec:
  vectorRef: vector-agent-complete
  transforms:
    config:
      type: "remap"
      inputs:
        - source1
      source: |
        .merged = "config"


---
apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  labels:
    app.kubernetes.io/name: vectorpipeline
    app.kubernetes.io/instance: vectorpipeline-sample
    app.kubernetes.io/part-of: vector-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vector-operator
  name: vectorpipeline-fail
spec:
  vectorRef: vector-not-here
  sources:
    source1:
      type: "kubernetes_logs"
      extra_label_selector: "app!=testdeployment"
    source2:
      type: "kubernetes_logs"
      extra_label_selector: "app!=testdeployment1"
  transforms:
    remap:
      type: "remap"
      inputs:
        - source1
      source: |
        .@timestamp = del(.timestamp)
        .testField = "testValuevalue"
    filter:
      type: "filter"
      inputs:
        - source2
      condition:
        type: "vrl"
        source: ".status != 200"
  sinks:
    test222:
      type: "console"
      encoding:
        codec: "json"
      inputs:
        - filter
        - remap
