apiVersion: vector.zcentric.com/v1alpha1
kind: Vector
metadata:
  name: vector-agent-minimal
spec:
  type: agent
  image: "timberio/vector:0.38.0-distroless-libc"
  api:
    enabled: false
---
apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vectorpipeline-minimal
spec:
  vectorRef: vector-agent-minimal
  sources:
    source1:
      type: "kubernetes_logs"
  sinks:
    console:
      type: "console"
      encoding:
        codec: "json"
      inputs:
        - source1
      buffer:
        type: "memory"
        max_size: 1000000
        max_age: 60
