apiVersion: vector.zcentric.com/v1alpha1
kind: VectorAggregator
metadata:
  name: vector-aggregator-complete
spec:
  image: "timberio/vector:0.38.0-distroless-libc"
  # Optional deployment configuration
  replicas: 3               # Default value is 1
  # Optional API configuration
  api:
    address: "0.0.0.0:8686"  # Default value
    enabled: true            # Enable API for monitoring
    playground: false        # Enable GraphQL playground for testing
  # Optional Vector configuration
  data_dir: "/tmp/vector-data-dir"  # Default value
  expire_metrics_secs: 30           # Default value
  # Optional ServiceAccount configuration
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/vector-role"  # Example AWS IRSA annotation
  # Optional tolerations configuration
  tolerations:
    - operator: Exists
  # Environment variables configuration
  env:
    - name: VECTOR_BUFFER_SIZE
      value: "1048576" # 1MB buffer size
    - name: VECTOR_CONCURRENCY
      value: "4" # Number of concurrent tasks
    - name: VECTOR_ACKNOWLEDGEMENTS
      value: "true"
    - name: VECTOR_CUSTOM_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: vector-aggregator-config
          key: endpoint
    - name: VECTOR_COMPRESSION_ENABLED
      value: "true"
    - name: VECTOR_AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: vector-aws-credentials
          key: access-key-id
    - name: VECTOR_AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: vector-aws-credentials
          key: secret-access-key
  # Resource requirements configuration
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "2Gi"
  # Topology spread constraints for high availability
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: vector
          app.kubernetes.io/component: aggregator
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: vector
          app.kubernetes.io/component: aggregator
---
apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vectorpipeline-aggregator-complete
spec:
  vectorRef: vector-aggregator-complete
  sources:
    source1:
      type: "kubernetes_logs"
  sinks:
    console:
      type: "console"
      encoding:
        codec: "json"
      inputs:
        - source1