apiVersion: vector.zcentric.com/v1alpha1
kind: VectorAggregator
metadata:
  name: vector-aggregator-minimal
spec:
  image: "timberio/vector:0.38.0-distroless-libc"
---

apiVersion: vector.zcentric.com/v1alpha1
kind: VectorPipeline
metadata:
  name: vector-aggregator-minimal-base
spec:
  vectorRef: vector-aggregator-minimal
  sources:
    logs:
      type: "kubernetes_logs"
  sinks:
    console:
      type: "console"
      inputs: ["logs"]
      encoding:
        codec: "json"