name: Go Tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Install setup-envtest
      run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

    - name: Set up Envtest
      run: |
        setup-envtest use 1.28.0
        echo "KUBEBUILDER_ASSETS=$(setup-envtest use 1.28.0 --bin-dir /tmp/envtest -p path)" >> $GITHUB_ENV

    - name: Run unit tests
      run: go test -v ./internal/controller/... -coverprofile=coverage.out

    - name: Run e2e tests
      run: go test -v ./test/e2e/... -coverprofile=e2e-coverage.out

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.out,./e2e-coverage.out
        flags: unittests,e2etests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
