name: Renovate Dependencies
on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      dry_run:
        description: "Enable to perform a dry run"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  id-token: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@7743ec9e19ceeb61a3862c5d4131e6710195af11 # v40.3.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
        env:
          RENOVATE_DRY_RUN: ${{ github.event_name == 'schedule' && 'false' || github.event.inputs.dry_run }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}